# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/Pri_Enc/Pri_Enc.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/Pri_Enc/Pri_Enc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Xilinx/Pri_Enc/Pri_Enc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib G:/Pri_Enc/Pri_Enc.srcs/sources_1/imports/new/priority_encoder1.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/Pri_Enc/Pri_Enc.srcs/constrs_1/new/priority_encoder.xdc
set_property used_in_implementation false [get_files G:/Pri_Enc/Pri_Enc.srcs/constrs_1/new/priority_encoder.xdc]


synth_design -top priority_encoder -part xc7a100tcsg324-1


write_checkpoint -force -noxdef priority_encoder.dcp

catch { report_utilization -file priority_encoder_utilization_synth.rpt -pb priority_encoder_utilization_synth.pb }
